accounts:
  - name: alice
    coins: ["20000token", "200000000stake"]
    mnemonic: "surround miss nominee dream gap cross assault thank captain prosper drop duty group candy wealth weather scale put"
  - name: bob
    coins: ["10000token", "100000000stake"]
validator:
  name: alice
  staked: "100000000stake"
  mnemonic: "surround miss nominee dream gap cross assault thank captain prosper drop duty group candy wealth weather scale put"
client:
  vuex:
    path: "vue/src/store"
  openapi:
    path: "docs/static/openapi.yml"
faucet:
  name: bob
  coins: ["5token", "100000stake"]
