// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: drife/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// this line is used by starport scaffolding # 3
type QueryGetCounterquoteRequest struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetCounterquoteRequest) Reset()         { *m = QueryGetCounterquoteRequest{} }
func (m *QueryGetCounterquoteRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetCounterquoteRequest) ProtoMessage()    {}
func (*QueryGetCounterquoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_746bd80633a5c3d2, []int{0}
}
func (m *QueryGetCounterquoteRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCounterquoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCounterquoteRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCounterquoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCounterquoteRequest.Merge(m, src)
}
func (m *QueryGetCounterquoteRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCounterquoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCounterquoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCounterquoteRequest proto.InternalMessageInfo

func (m *QueryGetCounterquoteRequest) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type QueryGetCounterquoteResponse struct {
	Counterquote *Counterquote `protobuf:"bytes,1,opt,name=Counterquote,proto3" json:"Counterquote,omitempty"`
}

func (m *QueryGetCounterquoteResponse) Reset()         { *m = QueryGetCounterquoteResponse{} }
func (m *QueryGetCounterquoteResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetCounterquoteResponse) ProtoMessage()    {}
func (*QueryGetCounterquoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_746bd80633a5c3d2, []int{1}
}
func (m *QueryGetCounterquoteResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetCounterquoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetCounterquoteResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetCounterquoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetCounterquoteResponse.Merge(m, src)
}
func (m *QueryGetCounterquoteResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetCounterquoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetCounterquoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetCounterquoteResponse proto.InternalMessageInfo

func (m *QueryGetCounterquoteResponse) GetCounterquote() *Counterquote {
	if m != nil {
		return m.Counterquote
	}
	return nil
}

type QueryAllCounterquoteRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllCounterquoteRequest) Reset()         { *m = QueryAllCounterquoteRequest{} }
func (m *QueryAllCounterquoteRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllCounterquoteRequest) ProtoMessage()    {}
func (*QueryAllCounterquoteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_746bd80633a5c3d2, []int{2}
}
func (m *QueryAllCounterquoteRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllCounterquoteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllCounterquoteRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllCounterquoteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllCounterquoteRequest.Merge(m, src)
}
func (m *QueryAllCounterquoteRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllCounterquoteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllCounterquoteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllCounterquoteRequest proto.InternalMessageInfo

func (m *QueryAllCounterquoteRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllCounterquoteResponse struct {
	Counterquote []*Counterquote     `protobuf:"bytes,1,rep,name=Counterquote,proto3" json:"Counterquote,omitempty"`
	Pagination   *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllCounterquoteResponse) Reset()         { *m = QueryAllCounterquoteResponse{} }
func (m *QueryAllCounterquoteResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllCounterquoteResponse) ProtoMessage()    {}
func (*QueryAllCounterquoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_746bd80633a5c3d2, []int{3}
}
func (m *QueryAllCounterquoteResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllCounterquoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllCounterquoteResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllCounterquoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllCounterquoteResponse.Merge(m, src)
}
func (m *QueryAllCounterquoteResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllCounterquoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllCounterquoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllCounterquoteResponse proto.InternalMessageInfo

func (m *QueryAllCounterquoteResponse) GetCounterquote() []*Counterquote {
	if m != nil {
		return m.Counterquote
	}
	return nil
}

func (m *QueryAllCounterquoteResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetRideRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *QueryGetRideRequest) Reset()         { *m = QueryGetRideRequest{} }
func (m *QueryGetRideRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetRideRequest) ProtoMessage()    {}
func (*QueryGetRideRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_746bd80633a5c3d2, []int{4}
}
func (m *QueryGetRideRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetRideRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetRideRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetRideRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetRideRequest.Merge(m, src)
}
func (m *QueryGetRideRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetRideRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetRideRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetRideRequest proto.InternalMessageInfo

func (m *QueryGetRideRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type QueryGetRideResponse struct {
	Ride *Ride `protobuf:"bytes,1,opt,name=Ride,proto3" json:"Ride,omitempty"`
}

func (m *QueryGetRideResponse) Reset()         { *m = QueryGetRideResponse{} }
func (m *QueryGetRideResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetRideResponse) ProtoMessage()    {}
func (*QueryGetRideResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_746bd80633a5c3d2, []int{5}
}
func (m *QueryGetRideResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetRideResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetRideResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetRideResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetRideResponse.Merge(m, src)
}
func (m *QueryGetRideResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetRideResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetRideResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetRideResponse proto.InternalMessageInfo

func (m *QueryGetRideResponse) GetRide() *Ride {
	if m != nil {
		return m.Ride
	}
	return nil
}

type QueryAllRideRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllRideRequest) Reset()         { *m = QueryAllRideRequest{} }
func (m *QueryAllRideRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllRideRequest) ProtoMessage()    {}
func (*QueryAllRideRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_746bd80633a5c3d2, []int{6}
}
func (m *QueryAllRideRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllRideRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllRideRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllRideRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllRideRequest.Merge(m, src)
}
func (m *QueryAllRideRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllRideRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllRideRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllRideRequest proto.InternalMessageInfo

func (m *QueryAllRideRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllRideResponse struct {
	Ride       []*Ride             `protobuf:"bytes,1,rep,name=Ride,proto3" json:"Ride,omitempty"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllRideResponse) Reset()         { *m = QueryAllRideResponse{} }
func (m *QueryAllRideResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllRideResponse) ProtoMessage()    {}
func (*QueryAllRideResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_746bd80633a5c3d2, []int{7}
}
func (m *QueryAllRideResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllRideResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllRideResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllRideResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllRideResponse.Merge(m, src)
}
func (m *QueryAllRideResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllRideResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllRideResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllRideResponse proto.InternalMessageInfo

func (m *QueryAllRideResponse) GetRide() []*Ride {
	if m != nil {
		return m.Ride
	}
	return nil
}

func (m *QueryAllRideResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryGetCounterquoteRequest)(nil), "example.drife.drife.QueryGetCounterquoteRequest")
	proto.RegisterType((*QueryGetCounterquoteResponse)(nil), "example.drife.drife.QueryGetCounterquoteResponse")
	proto.RegisterType((*QueryAllCounterquoteRequest)(nil), "example.drife.drife.QueryAllCounterquoteRequest")
	proto.RegisterType((*QueryAllCounterquoteResponse)(nil), "example.drife.drife.QueryAllCounterquoteResponse")
	proto.RegisterType((*QueryGetRideRequest)(nil), "example.drife.drife.QueryGetRideRequest")
	proto.RegisterType((*QueryGetRideResponse)(nil), "example.drife.drife.QueryGetRideResponse")
	proto.RegisterType((*QueryAllRideRequest)(nil), "example.drife.drife.QueryAllRideRequest")
	proto.RegisterType((*QueryAllRideResponse)(nil), "example.drife.drife.QueryAllRideResponse")
}

func init() { proto.RegisterFile("drife/query.proto", fileDescriptor_746bd80633a5c3d2) }

var fileDescriptor_746bd80633a5c3d2 = []byte{
	// 527 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x94, 0xcf, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0xeb, 0xae, 0x80, 0x30, 0x88, 0x1f, 0x1e, 0x87, 0xad, 0x9b, 0xa2, 0x35, 0x88, 0xd2,
	0x21, 0xcd, 0xa6, 0xe3, 0x1f, 0xa0, 0xa0, 0xb1, 0x2b, 0xf4, 0x88, 0xc4, 0x21, 0x69, 0x4c, 0xb0,
	0xe4, 0xc6, 0x69, 0xec, 0xa0, 0x4d, 0x88, 0x03, 0x70, 0x47, 0x48, 0xfc, 0x05, 0x88, 0x3b, 0x7f,
	0x07, 0xc7, 0x49, 0x5c, 0x90, 0xb8, 0xa0, 0x96, 0x3f, 0x04, 0xc5, 0xf6, 0x20, 0x59, 0xdd, 0xac,
	0xa0, 0x5d, 0x5a, 0xc5, 0x7e, 0xdf, 0xf7, 0x3e, 0xef, 0xfb, 0xf2, 0x02, 0xaf, 0x47, 0x19, 0x7b,
	0x4e, 0xc9, 0x24, 0xa7, 0xd9, 0x21, 0x4e, 0x33, 0xa1, 0x04, 0x5a, 0xa5, 0x07, 0xc1, 0x38, 0xe5,
	0x14, 0xeb, 0x2b, 0xf3, 0xdb, 0xde, 0x8c, 0x85, 0x88, 0x39, 0x25, 0x41, 0xca, 0x48, 0x90, 0x24,
	0x42, 0x05, 0x8a, 0x89, 0x44, 0x1a, 0x49, 0xfb, 0xce, 0x48, 0xc8, 0xb1, 0x90, 0x24, 0x0c, 0xa4,
	0xcd, 0x45, 0x5e, 0xf6, 0x43, 0xaa, 0x82, 0x3e, 0x49, 0x83, 0x98, 0x25, 0x3a, 0xd8, 0xc6, 0x5e,
	0x33, 0x15, 0x33, 0x16, 0x51, 0x7b, 0xb2, 0x66, 0x4e, 0x46, 0x22, 0x4f, 0x14, 0xcd, 0x26, 0xb9,
	0x50, 0xf6, 0xc6, 0xdf, 0x81, 0x1b, 0x4f, 0x8a, 0x6c, 0xfb, 0x54, 0x3d, 0x2c, 0xdd, 0x0e, 0xe9,
	0x24, 0xa7, 0x52, 0xa1, 0x2b, 0xb0, 0xc9, 0xa2, 0x35, 0xb0, 0x05, 0x7a, 0xad, 0x61, 0x93, 0x45,
	0x3e, 0x85, 0x9b, 0xee, 0x70, 0x99, 0x8a, 0x44, 0x52, 0xb4, 0x07, 0x2f, 0x97, 0xcf, 0xb5, 0xf2,
	0xd2, 0x6e, 0x07, 0x3b, 0x1a, 0xc6, 0x95, 0x04, 0x15, 0x99, 0x4f, 0x2d, 0xd5, 0x80, 0x73, 0x17,
	0xd5, 0x23, 0x08, 0xff, 0x36, 0x6d, 0x6b, 0x74, 0xb1, 0x71, 0x08, 0x17, 0x0e, 0x61, 0xe3, 0xb6,
	0x75, 0x08, 0x3f, 0x0e, 0xe2, 0x63, 0xed, 0xb0, 0xa4, 0xf4, 0xbf, 0x00, 0xdb, 0xce, 0x5c, 0x9d,
	0x85, 0xed, 0xac, 0xfc, 0x47, 0x3b, 0x68, 0xbf, 0xc2, 0xdb, 0xd4, 0xbc, 0xb7, 0x4f, 0xe5, 0x35,
	0x0c, 0x15, 0xe0, 0x5b, 0x70, 0xf5, 0xd8, 0xfe, 0x21, 0x8b, 0x1c, 0x53, 0xba, 0xa8, 0xa7, 0xb4,
	0x07, 0x6f, 0x54, 0xc3, 0x6c, 0x3b, 0x3b, 0xb0, 0x55, 0x3c, 0x5b, 0xc7, 0xd6, 0x9d, 0x6d, 0x68,
	0x81, 0x0e, 0xf3, 0x9f, 0xd9, 0x6a, 0x03, 0xce, 0xcb, 0xd5, 0xce, 0xca, 0xfd, 0xf7, 0xc0, 0x62,
	0xfe, 0xc9, 0x3f, 0x87, 0xb9, 0xb2, 0x04, 0xe6, 0x99, 0xb9, 0xbb, 0xfb, 0xa3, 0x05, 0xcf, 0x69,
	0x20, 0xf4, 0x19, 0x54, 0x07, 0x8f, 0xee, 0x3a, 0x21, 0x6a, 0x36, 0xa7, 0xdd, 0xff, 0x07, 0x85,
	0x61, 0xf1, 0xf1, 0xdb, 0x6f, 0xbf, 0x3e, 0x36, 0x7b, 0xa8, 0x4b, 0xac, 0x94, 0x98, 0xb5, 0x9d,
	0x5f, 0x5e, 0xf2, 0x8a, 0x45, 0xaf, 0xd1, 0x27, 0x00, 0xaf, 0x96, 0x13, 0x0d, 0x38, 0xaf, 0x03,
	0x75, 0x2f, 0x53, 0x1d, 0xe8, 0x82, 0xb5, 0xf0, 0xb7, 0x35, 0xe8, 0x4d, 0xd4, 0x39, 0x15, 0x14,
	0xbd, 0x03, 0x66, 0x98, 0xa8, 0x57, 0xeb, 0x47, 0xe9, 0xfd, 0x6a, 0x6f, 0x2f, 0x11, 0x69, 0x41,
	0xba, 0x1a, 0x64, 0x0b, 0x79, 0x4e, 0x90, 0xe2, 0x03, 0x68, 0x9c, 0x7a, 0x03, 0xe0, 0x85, 0x42,
	0x58, 0x38, 0xd4, 0xab, 0xed, 0x77, 0x49, 0x90, 0x13, 0xaf, 0xac, 0xdf, 0xd1, 0x20, 0x1b, 0x68,
	0x7d, 0x21, 0xc8, 0x83, 0xfb, 0x5f, 0xa7, 0x1e, 0x38, 0x9a, 0x7a, 0xe0, 0xe7, 0xd4, 0x03, 0x1f,
	0x66, 0x5e, 0xe3, 0x68, 0xe6, 0x35, 0xbe, 0xcf, 0xbc, 0xc6, 0xd3, 0x6e, 0xcc, 0xd4, 0x8b, 0x3c,
	0xc4, 0x23, 0x31, 0x3e, 0x21, 0x3f, 0xb0, 0xff, 0xea, 0x30, 0xa5, 0x32, 0x3c, 0xaf, 0x3f, 0xd9,
	0xf7, 0x7e, 0x07, 0x00, 0x00, 0xff, 0xff, 0x89, 0x44, 0x03, 0xc4, 0x52, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Queries a counterquote by id.
	Counterquote(ctx context.Context, in *QueryGetCounterquoteRequest, opts ...grpc.CallOption) (*QueryGetCounterquoteResponse, error)
	// Queries a list of counterquote items.
	CounterquoteAll(ctx context.Context, in *QueryAllCounterquoteRequest, opts ...grpc.CallOption) (*QueryAllCounterquoteResponse, error)
	Ride(ctx context.Context, in *QueryGetRideRequest, opts ...grpc.CallOption) (*QueryGetRideResponse, error)
	RideAll(ctx context.Context, in *QueryAllRideRequest, opts ...grpc.CallOption) (*QueryAllRideResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Counterquote(ctx context.Context, in *QueryGetCounterquoteRequest, opts ...grpc.CallOption) (*QueryGetCounterquoteResponse, error) {
	out := new(QueryGetCounterquoteResponse)
	err := c.cc.Invoke(ctx, "/example.drife.drife.Query/Counterquote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) CounterquoteAll(ctx context.Context, in *QueryAllCounterquoteRequest, opts ...grpc.CallOption) (*QueryAllCounterquoteResponse, error) {
	out := new(QueryAllCounterquoteResponse)
	err := c.cc.Invoke(ctx, "/example.drife.drife.Query/CounterquoteAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Ride(ctx context.Context, in *QueryGetRideRequest, opts ...grpc.CallOption) (*QueryGetRideResponse, error) {
	out := new(QueryGetRideResponse)
	err := c.cc.Invoke(ctx, "/example.drife.drife.Query/Ride", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) RideAll(ctx context.Context, in *QueryAllRideRequest, opts ...grpc.CallOption) (*QueryAllRideResponse, error) {
	out := new(QueryAllRideResponse)
	err := c.cc.Invoke(ctx, "/example.drife.drife.Query/RideAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Queries a counterquote by id.
	Counterquote(context.Context, *QueryGetCounterquoteRequest) (*QueryGetCounterquoteResponse, error)
	// Queries a list of counterquote items.
	CounterquoteAll(context.Context, *QueryAllCounterquoteRequest) (*QueryAllCounterquoteResponse, error)
	Ride(context.Context, *QueryGetRideRequest) (*QueryGetRideResponse, error)
	RideAll(context.Context, *QueryAllRideRequest) (*QueryAllRideResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Counterquote(ctx context.Context, req *QueryGetCounterquoteRequest) (*QueryGetCounterquoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Counterquote not implemented")
}
func (*UnimplementedQueryServer) CounterquoteAll(ctx context.Context, req *QueryAllCounterquoteRequest) (*QueryAllCounterquoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CounterquoteAll not implemented")
}
func (*UnimplementedQueryServer) Ride(ctx context.Context, req *QueryGetRideRequest) (*QueryGetRideResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ride not implemented")
}
func (*UnimplementedQueryServer) RideAll(ctx context.Context, req *QueryAllRideRequest) (*QueryAllRideResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RideAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Counterquote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetCounterquoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Counterquote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.drife.drife.Query/Counterquote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Counterquote(ctx, req.(*QueryGetCounterquoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_CounterquoteAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllCounterquoteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).CounterquoteAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.drife.drife.Query/CounterquoteAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).CounterquoteAll(ctx, req.(*QueryAllCounterquoteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Ride_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetRideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Ride(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.drife.drife.Query/Ride",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Ride(ctx, req.(*QueryGetRideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_RideAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllRideRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).RideAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.drife.drife.Query/RideAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).RideAll(ctx, req.(*QueryAllRideRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "example.drife.drife.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Counterquote",
			Handler:    _Query_Counterquote_Handler,
		},
		{
			MethodName: "CounterquoteAll",
			Handler:    _Query_CounterquoteAll_Handler,
		},
		{
			MethodName: "Ride",
			Handler:    _Query_Ride_Handler,
		},
		{
			MethodName: "RideAll",
			Handler:    _Query_RideAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "drife/query.proto",
}

func (m *QueryGetCounterquoteRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCounterquoteRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCounterquoteRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetCounterquoteResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetCounterquoteResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetCounterquoteResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Counterquote != nil {
		{
			size, err := m.Counterquote.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllCounterquoteRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllCounterquoteRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllCounterquoteRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllCounterquoteResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllCounterquoteResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllCounterquoteResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Counterquote) > 0 {
		for iNdEx := len(m.Counterquote) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Counterquote[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetRideRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetRideRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetRideRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Id) > 0 {
		i -= len(m.Id)
		copy(dAtA[i:], m.Id)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.Id)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetRideResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetRideResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetRideResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Ride != nil {
		{
			size, err := m.Ride.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllRideRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllRideRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllRideRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllRideResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllRideResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllRideResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Ride) > 0 {
		for iNdEx := len(m.Ride) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Ride[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryGetCounterquoteRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovQuery(uint64(m.Id))
	}
	return n
}

func (m *QueryGetCounterquoteResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Counterquote != nil {
		l = m.Counterquote.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllCounterquoteRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllCounterquoteResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Counterquote) > 0 {
		for _, e := range m.Counterquote {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetRideRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Id)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetRideResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Ride != nil {
		l = m.Ride.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllRideRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllRideResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Ride) > 0 {
		for _, e := range m.Ride {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryGetCounterquoteRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCounterquoteRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCounterquoteRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetCounterquoteResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetCounterquoteResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetCounterquoteResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Counterquote", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Counterquote == nil {
				m.Counterquote = &Counterquote{}
			}
			if err := m.Counterquote.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllCounterquoteRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllCounterquoteRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllCounterquoteRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllCounterquoteResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllCounterquoteResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllCounterquoteResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Counterquote", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Counterquote = append(m.Counterquote, &Counterquote{})
			if err := m.Counterquote[len(m.Counterquote)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetRideRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetRideRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetRideRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Id = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetRideResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetRideResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetRideResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ride", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Ride == nil {
				m.Ride = &Ride{}
			}
			if err := m.Ride.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllRideRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllRideRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllRideRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllRideResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllRideResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllRideResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Ride", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Ride = append(m.Ride, &Ride{})
			if err := m.Ride[len(m.Ride)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
