// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: drife/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// this line is used by starport scaffolding # proto/tx/message
type MsgCreateCounterquote struct {
	Creator        string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	PremiumPercent int64  `protobuf:"varint,2,opt,name=premiumPercent,proto3" json:"premiumPercent,omitempty"`
	RideId         int64  `protobuf:"varint,3,opt,name=rideId,proto3" json:"rideId,omitempty"`
}

func (m *MsgCreateCounterquote) Reset()         { *m = MsgCreateCounterquote{} }
func (m *MsgCreateCounterquote) String() string { return proto.CompactTextString(m) }
func (*MsgCreateCounterquote) ProtoMessage()    {}
func (*MsgCreateCounterquote) Descriptor() ([]byte, []int) {
	return fileDescriptor_bba899a99e80cb2b, []int{0}
}
func (m *MsgCreateCounterquote) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateCounterquote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateCounterquote.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateCounterquote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateCounterquote.Merge(m, src)
}
func (m *MsgCreateCounterquote) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateCounterquote) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateCounterquote.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateCounterquote proto.InternalMessageInfo

func (m *MsgCreateCounterquote) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateCounterquote) GetPremiumPercent() int64 {
	if m != nil {
		return m.PremiumPercent
	}
	return 0
}

func (m *MsgCreateCounterquote) GetRideId() int64 {
	if m != nil {
		return m.RideId
	}
	return 0
}

type MsgCreateCounterquoteResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgCreateCounterquoteResponse) Reset()         { *m = MsgCreateCounterquoteResponse{} }
func (m *MsgCreateCounterquoteResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateCounterquoteResponse) ProtoMessage()    {}
func (*MsgCreateCounterquoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bba899a99e80cb2b, []int{1}
}
func (m *MsgCreateCounterquoteResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateCounterquoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateCounterquoteResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateCounterquoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateCounterquoteResponse.Merge(m, src)
}
func (m *MsgCreateCounterquoteResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateCounterquoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateCounterquoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateCounterquoteResponse proto.InternalMessageInfo

func (m *MsgCreateCounterquoteResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgUpdateCounterquote struct {
	Creator        string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id             uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
	PremiumPercent int64  `protobuf:"varint,3,opt,name=premiumPercent,proto3" json:"premiumPercent,omitempty"`
	RideId         int64  `protobuf:"varint,4,opt,name=rideId,proto3" json:"rideId,omitempty"`
}

func (m *MsgUpdateCounterquote) Reset()         { *m = MsgUpdateCounterquote{} }
func (m *MsgUpdateCounterquote) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateCounterquote) ProtoMessage()    {}
func (*MsgUpdateCounterquote) Descriptor() ([]byte, []int) {
	return fileDescriptor_bba899a99e80cb2b, []int{2}
}
func (m *MsgUpdateCounterquote) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateCounterquote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateCounterquote.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateCounterquote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateCounterquote.Merge(m, src)
}
func (m *MsgUpdateCounterquote) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateCounterquote) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateCounterquote.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateCounterquote proto.InternalMessageInfo

func (m *MsgUpdateCounterquote) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdateCounterquote) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MsgUpdateCounterquote) GetPremiumPercent() int64 {
	if m != nil {
		return m.PremiumPercent
	}
	return 0
}

func (m *MsgUpdateCounterquote) GetRideId() int64 {
	if m != nil {
		return m.RideId
	}
	return 0
}

type MsgUpdateCounterquoteResponse struct {
}

func (m *MsgUpdateCounterquoteResponse) Reset()         { *m = MsgUpdateCounterquoteResponse{} }
func (m *MsgUpdateCounterquoteResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateCounterquoteResponse) ProtoMessage()    {}
func (*MsgUpdateCounterquoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bba899a99e80cb2b, []int{3}
}
func (m *MsgUpdateCounterquoteResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateCounterquoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateCounterquoteResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateCounterquoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateCounterquoteResponse.Merge(m, src)
}
func (m *MsgUpdateCounterquoteResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateCounterquoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateCounterquoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateCounterquoteResponse proto.InternalMessageInfo

type MsgDeleteCounterquote struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	Id      uint64 `protobuf:"varint,2,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgDeleteCounterquote) Reset()         { *m = MsgDeleteCounterquote{} }
func (m *MsgDeleteCounterquote) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteCounterquote) ProtoMessage()    {}
func (*MsgDeleteCounterquote) Descriptor() ([]byte, []int) {
	return fileDescriptor_bba899a99e80cb2b, []int{4}
}
func (m *MsgDeleteCounterquote) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteCounterquote) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteCounterquote.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteCounterquote) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteCounterquote.Merge(m, src)
}
func (m *MsgDeleteCounterquote) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteCounterquote) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteCounterquote.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteCounterquote proto.InternalMessageInfo

func (m *MsgDeleteCounterquote) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgDeleteCounterquote) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgDeleteCounterquoteResponse struct {
}

func (m *MsgDeleteCounterquoteResponse) Reset()         { *m = MsgDeleteCounterquoteResponse{} }
func (m *MsgDeleteCounterquoteResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteCounterquoteResponse) ProtoMessage()    {}
func (*MsgDeleteCounterquoteResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bba899a99e80cb2b, []int{5}
}
func (m *MsgDeleteCounterquoteResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteCounterquoteResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteCounterquoteResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteCounterquoteResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteCounterquoteResponse.Merge(m, src)
}
func (m *MsgDeleteCounterquoteResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteCounterquoteResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteCounterquoteResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteCounterquoteResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateCounterquote)(nil), "example.drife.drife.MsgCreateCounterquote")
	proto.RegisterType((*MsgCreateCounterquoteResponse)(nil), "example.drife.drife.MsgCreateCounterquoteResponse")
	proto.RegisterType((*MsgUpdateCounterquote)(nil), "example.drife.drife.MsgUpdateCounterquote")
	proto.RegisterType((*MsgUpdateCounterquoteResponse)(nil), "example.drife.drife.MsgUpdateCounterquoteResponse")
	proto.RegisterType((*MsgDeleteCounterquote)(nil), "example.drife.drife.MsgDeleteCounterquote")
	proto.RegisterType((*MsgDeleteCounterquoteResponse)(nil), "example.drife.drife.MsgDeleteCounterquoteResponse")
}

func init() { proto.RegisterFile("drife/tx.proto", fileDescriptor_bba899a99e80cb2b) }

var fileDescriptor_bba899a99e80cb2b = []byte{
	// 344 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x93, 0x41, 0x4b, 0xf3, 0x30,
	0x18, 0xc7, 0x97, 0x76, 0xec, 0xe5, 0xcd, 0x61, 0x87, 0x88, 0x52, 0x06, 0xd6, 0xd1, 0xc3, 0x18,
	0x1e, 0x5a, 0x98, 0x5f, 0x40, 0x9d, 0x17, 0x0f, 0x03, 0x29, 0x78, 0xf1, 0xb6, 0x35, 0x8f, 0x33,
	0xb0, 0x2e, 0x59, 0x9a, 0xc2, 0x3c, 0xfa, 0x0d, 0xfc, 0x58, 0x1e, 0x77, 0xf4, 0x28, 0xeb, 0xc1,
	0xaf, 0x21, 0x4b, 0x5b, 0x51, 0x9b, 0xe0, 0xf0, 0xd2, 0x92, 0x27, 0x7f, 0x9e, 0xdf, 0x8f, 0xe7,
	0x21, 0xb8, 0x4b, 0x25, 0xbb, 0x87, 0x48, 0xad, 0x43, 0x21, 0xb9, 0xe2, 0xe4, 0x00, 0xd6, 0xd3,
	0x54, 0x2c, 0x20, 0xd4, 0xf5, 0xf2, 0xdb, 0xf3, 0xca, 0x50, 0xc2, 0xf3, 0xa5, 0x02, 0xb9, 0xca,
	0xb9, 0x82, 0x32, 0x1e, 0xac, 0xf0, 0xe1, 0x24, 0x9b, 0x8f, 0x25, 0x4c, 0x15, 0x8c, 0xbf, 0x5c,
	0x13, 0x0f, 0xff, 0x4b, 0x76, 0x55, 0x2e, 0x3d, 0xd4, 0x47, 0xc3, 0xff, 0x71, 0x7d, 0x24, 0x03,
	0xdc, 0x15, 0x12, 0x52, 0x96, 0xa7, 0x37, 0x20, 0x13, 0x58, 0x2a, 0xcf, 0xe9, 0xa3, 0xa1, 0x1b,
	0xff, 0xa8, 0x92, 0x23, 0xdc, 0x91, 0x8c, 0xc2, 0x35, 0xf5, 0x5c, 0x7d, 0x5f, 0x9d, 0x82, 0x08,
	0x1f, 0x1b, 0x91, 0x31, 0x64, 0x82, 0x2f, 0x33, 0x20, 0x5d, 0xec, 0x30, 0xaa, 0xa9, 0xed, 0xd8,
	0x61, 0x34, 0x78, 0x42, 0x5a, 0xf2, 0x56, 0xd0, 0xfd, 0x25, 0xcb, 0x1e, 0x4e, 0xdd, 0xc3, 0x20,
	0xed, 0xfe, 0x22, 0xdd, 0xfe, 0x26, 0x7d, 0xa2, 0xa5, 0x9b, 0x0a, 0xb5, 0x74, 0x70, 0xa1, 0x1d,
	0xaf, 0x60, 0x01, 0x7f, 0x75, 0xac, 0x18, 0xcd, 0x16, 0x35, 0x63, 0xf4, 0xee, 0x60, 0x77, 0x92,
	0xcd, 0x89, 0xc2, 0xc4, 0xb0, 0xb1, 0xd3, 0xd0, 0xb0, 0xfa, 0xd0, 0x38, 0xea, 0xde, 0x68, 0xff,
	0xec, 0xe7, 0x5a, 0x14, 0x26, 0x86, 0x15, 0x58, 0xa9, 0xcd, 0xac, 0x9d, 0x6a, 0x9f, 0xeb, 0x8e,
	0x6a, 0x18, 0xaa, 0x95, 0xda, 0xcc, 0xda, 0xa9, 0xf6, 0x49, 0x5f, 0x9e, 0xbf, 0x6c, 0x7d, 0xb4,
	0xd9, 0xfa, 0xe8, 0x6d, 0xeb, 0xa3, 0xe7, 0xc2, 0x6f, 0x6d, 0x0a, 0xbf, 0xf5, 0x5a, 0xf8, 0xad,
	0xbb, 0xc1, 0x9c, 0xa9, 0x87, 0x7c, 0x16, 0x26, 0x3c, 0x8d, 0xaa, 0xbe, 0x51, 0xf9, 0xba, 0xd6,
	0xd5, 0x5f, 0x3d, 0x0a, 0xc8, 0x66, 0x1d, 0xfd, 0xbe, 0xce, 0x3e, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x06, 0xd7, 0x91, 0x24, 0xa0, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	// this line is used by starport scaffolding # proto/tx/rpc
	CreateCounterquote(ctx context.Context, in *MsgCreateCounterquote, opts ...grpc.CallOption) (*MsgCreateCounterquoteResponse, error)
	UpdateCounterquote(ctx context.Context, in *MsgUpdateCounterquote, opts ...grpc.CallOption) (*MsgUpdateCounterquoteResponse, error)
	DeleteCounterquote(ctx context.Context, in *MsgDeleteCounterquote, opts ...grpc.CallOption) (*MsgDeleteCounterquoteResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateCounterquote(ctx context.Context, in *MsgCreateCounterquote, opts ...grpc.CallOption) (*MsgCreateCounterquoteResponse, error) {
	out := new(MsgCreateCounterquoteResponse)
	err := c.cc.Invoke(ctx, "/example.drife.drife.Msg/CreateCounterquote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateCounterquote(ctx context.Context, in *MsgUpdateCounterquote, opts ...grpc.CallOption) (*MsgUpdateCounterquoteResponse, error) {
	out := new(MsgUpdateCounterquoteResponse)
	err := c.cc.Invoke(ctx, "/example.drife.drife.Msg/UpdateCounterquote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteCounterquote(ctx context.Context, in *MsgDeleteCounterquote, opts ...grpc.CallOption) (*MsgDeleteCounterquoteResponse, error) {
	out := new(MsgDeleteCounterquoteResponse)
	err := c.cc.Invoke(ctx, "/example.drife.drife.Msg/DeleteCounterquote", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	// this line is used by starport scaffolding # proto/tx/rpc
	CreateCounterquote(context.Context, *MsgCreateCounterquote) (*MsgCreateCounterquoteResponse, error)
	UpdateCounterquote(context.Context, *MsgUpdateCounterquote) (*MsgUpdateCounterquoteResponse, error)
	DeleteCounterquote(context.Context, *MsgDeleteCounterquote) (*MsgDeleteCounterquoteResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateCounterquote(ctx context.Context, req *MsgCreateCounterquote) (*MsgCreateCounterquoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCounterquote not implemented")
}
func (*UnimplementedMsgServer) UpdateCounterquote(ctx context.Context, req *MsgUpdateCounterquote) (*MsgUpdateCounterquoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCounterquote not implemented")
}
func (*UnimplementedMsgServer) DeleteCounterquote(ctx context.Context, req *MsgDeleteCounterquote) (*MsgDeleteCounterquoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCounterquote not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateCounterquote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateCounterquote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateCounterquote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.drife.drife.Msg/CreateCounterquote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateCounterquote(ctx, req.(*MsgCreateCounterquote))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateCounterquote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateCounterquote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateCounterquote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.drife.drife.Msg/UpdateCounterquote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateCounterquote(ctx, req.(*MsgUpdateCounterquote))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteCounterquote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteCounterquote)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteCounterquote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/example.drife.drife.Msg/DeleteCounterquote",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteCounterquote(ctx, req.(*MsgDeleteCounterquote))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "example.drife.drife.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCounterquote",
			Handler:    _Msg_CreateCounterquote_Handler,
		},
		{
			MethodName: "UpdateCounterquote",
			Handler:    _Msg_UpdateCounterquote_Handler,
		},
		{
			MethodName: "DeleteCounterquote",
			Handler:    _Msg_DeleteCounterquote_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "drife/tx.proto",
}

func (m *MsgCreateCounterquote) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateCounterquote) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateCounterquote) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RideId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.RideId))
		i--
		dAtA[i] = 0x18
	}
	if m.PremiumPercent != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PremiumPercent))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateCounterquoteResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateCounterquoteResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateCounterquoteResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateCounterquote) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateCounterquote) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateCounterquote) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RideId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.RideId))
		i--
		dAtA[i] = 0x20
	}
	if m.PremiumPercent != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.PremiumPercent))
		i--
		dAtA[i] = 0x18
	}
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateCounterquoteResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateCounterquoteResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateCounterquoteResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDeleteCounterquote) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteCounterquote) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteCounterquote) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteCounterquoteResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteCounterquoteResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteCounterquoteResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateCounterquote) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.PremiumPercent != 0 {
		n += 1 + sovTx(uint64(m.PremiumPercent))
	}
	if m.RideId != 0 {
		n += 1 + sovTx(uint64(m.RideId))
	}
	return n
}

func (m *MsgCreateCounterquoteResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgUpdateCounterquote) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	if m.PremiumPercent != 0 {
		n += 1 + sovTx(uint64(m.PremiumPercent))
	}
	if m.RideId != 0 {
		n += 1 + sovTx(uint64(m.RideId))
	}
	return n
}

func (m *MsgUpdateCounterquoteResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDeleteCounterquote) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgDeleteCounterquoteResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateCounterquote) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateCounterquote: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateCounterquote: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PremiumPercent", wireType)
			}
			m.PremiumPercent = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PremiumPercent |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RideId", wireType)
			}
			m.RideId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RideId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateCounterquoteResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateCounterquoteResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateCounterquoteResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateCounterquote) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateCounterquote: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateCounterquote: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PremiumPercent", wireType)
			}
			m.PremiumPercent = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PremiumPercent |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RideId", wireType)
			}
			m.RideId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RideId |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateCounterquoteResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateCounterquoteResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateCounterquoteResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteCounterquote) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteCounterquote: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteCounterquote: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteCounterquoteResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteCounterquoteResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteCounterquoteResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
